# Generated by Django 5.0.4 on 2024-04-20 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="会議室名")),
                (
                    "available_user_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "一般"), (2, "上級")],
                        default=0,
                        verbose_name="利用可能ユーザー種別",
                    ),
                ),
            ],
            options={
                "verbose_name": "会議室",
                "verbose_name_plural": "会議室",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="開始日時")),
                ("end", models.DateTimeField(verbose_name="終了日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="予約ユーザー",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservation.room",
                        verbose_name="会議室",
                    ),
                ),
            ],
            options={
                "verbose_name": "予約",
                "verbose_name_plural": "予約",
            },
        ),
    ]
